enable shell option 'set -e'

diff --git a/tiny-rc b/tiny-rc
--- a/tiny-rc
+++ b/tiny-rc
@@ -3,6 +3,9 @@
 ## Tiny rc (run commands) script for Linux containers
 ##
 
+## When command fails, the shell exit immediately.
+set -e
+
 ##
 ## Environments
 ##
@@ -171,13 +174,13 @@ for i in `LC_ALL=C; ls ${TINYRC_INIT_DIR}/*`; do
 
     log "${script} is executable"
 
-    echo "${script}" | grep ".unit" > /dev/null
+    echo "${script}" | grep ".unit" > /dev/null &&:
     if [ $? -eq 0 ]; then
         log "mark '${script}' as unit" ${LOG_INFO}
         unit_list="${unit_list} ${script}"
     fi
 
-    echo "${script}" | grep ".service$" > /dev/null
+    echo "${script}" | grep ".service$" > /dev/null &&:
     if [ $? -eq 0 ]; then
         log "mark '${script}' as service" ${LOG_INFO}
         service_list="${service_list} ${script}"
@@ -243,17 +246,18 @@ pid_file=`mktemp`
 ret_file=`mktemp`
 
 (
+    set -e
     trap ":" HUP INT QUIT TERM
 
     $* &
-    pid=$!
+    pid=${!}
 
     tmpfile=`mktemp`
     echo ${pid} > ${tmpfile}
     mv ${tmpfile} ${pid_file}
 
-    wait ${pid}
-    ret=$?
+    wait ${pid} &&:
+    ret=${?}
 
     tmpfile=`mktemp`
     echo ${ret} > ${tmpfile}
